### ISSUE TITLE
win10重装系统后遇到以下报错

### ISSUE THREAD

**Issue by sadnessyuki** [maskrs/DBD_AFK_TOOL#15]
Traceback (most recent call last):
  File "Coord.py", line 12, in reglw
  File "comtypes\client\__init__.py", line 204, in CreateObject
  File "comtypes\GUID.py", line 86, in from_progid
  File "_ctypes/callproc.c", line 998, in GetResult
OSError: [WinError -2147221005] 无效的类字符串

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 23, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 499, in exec_module
  File "Coord.py", line 35, in <module>
  File "Coord.py", line 15, in reglw
  File "comtypes\client\__init__.py", line 204, in CreateObject
  File "comtypes\GUID.py", line 86, in from_progid
  File "_ctypes/callproc.c", line 998, in GetResult
OSError: [WinError -2147221005] 无效的类字符串

老哥能救一下吗

**Comment by maskrs** [comment]
管理员运行bat文件即可
