### ISSUE TITLE
管理员运行了也不行

### ISSUE THREAD

**Issue by island33** [maskrs/DBD_AFK_TOOL#17]
手动注册了也不行就是打不开大佬求教
![Uploading 7F1B3646-B0CB-49FD-A8DB-BC6BC7F8F486.jpeg…]()

**Comment by maskrs** [comment]
截图无法加载，请给出完整的报错信息。

**Comment by island33** [comment]
Traceback (most recent call last):
  File "Coord.py", line 12, in reglw
  File "comtypes\client\__init__.py", line 204, in CreateObject
  File "comtypes\GUID.py", line 86, in from_progid
  File "_ctypes/callproc.c", line 998, in GetResult
OSError: [WinError -2147221005] 无效的类字符串

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 22, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 499, in exec_module
  File "Coord.py", line 35, in <module>
  File "Coord.py", line 15, in reglw
  File "comtypes\client\__init__.py", line 204, in CreateObject
  File "comtypes\GUID.py", line 86, in from_progid
  File "_ctypes/callproc.c", line 998, in GetResult
OSError: [WinError -2147221005] 无效的类字符串

**Comment by island33** [comment]
![QQ浏览器截图20230309083942](https://user-images.githubusercontent.com/127336989/223885260-692dfcce-89a7-403b-b3ad-cd17cc44b340.png)

**Comment by maskrs** [comment]
> ![QQ浏览器截图20230309083942](https://user-images.githubusercontent.com/127336989/223885260-692dfcce-89a7-403b-b3ad-cd17cc44b340.png)

权限不够，使用管理员注册
